// Version: V1.0 (2026-10-05) — admin-site/scripts/build-demos.js — V1.0
// SkyTech_WebsiteDeveloper: builds demo websites from design files and writes the database update.
//   Input : demo-sites/designs/<slug>.json      (unique design + wording for one business)
//           data/samples/SkyTech_Leads_Sample100.csv (public facts: phone, email, address)
//   Output: demo-sites/<slug>/index.html         (self-contained page)
//           demo-sites/manifest.csv              (one row per demo, never duplicated)
//           sql/05_demo_sites_built.sql          (adds each demo to dbo.DemoSites and marks the lead DemoBuilt; safe to re-run)
// Usage (from the admin-site folder):  npm run build-demos            (all designs)
//                                       npm run build-demos -- c-and-a-plumbing-20723   (one or more slugs)
// After the demos are in SkyTechCRM, edit them in the Admin site (Demo sites tab); edits there win.
'use strict';
const fs = require('fs');
const path = require('path');
const { render, TEMPLATE_VERSION } = require('../src/demo/render');

const ROOT = process.env.SKYTECH_ROOT || path.resolve(__dirname, '..', '..');
const DESIGNS = path.join(ROOT, 'demo-sites', 'designs');
const CSV = path.join(ROOT, 'data', 'samples', 'SkyTech_Leads_Sample100.csv');
const SQL = path.join(ROOT, 'sql', '05_demo_sites_built.sql');
const TODAY = new Date().toISOString().slice(0, 10);
const FIELDS = ['Slug', 'Layout', 'Theme', 'PrimaryColor', 'AccentColor', 'BackgroundColor', 'HeadingFont', 'BodyFont', 'LogoText', 'LogoShape',
  'Illustration', 'BrandName', 'Tagline', 'Headline', 'Subheadline', 'About', 'Services', 'Highlights', 'Steps', 'ServiceAreas', 'CallToAction',
  'DisclosureNote', 'Status', 'Notes'];

function parseCSV(text) {
  const rows = []; let row = [], cell = '', q = false;
  text = text.replace(/^﻿/, '');
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (q) { if (ch === '"' && text[i + 1] === '"') { cell += '"'; i++; } else if (ch === '"') q = false; else cell += ch; }
    else if (ch === '"') q = true; else if (ch === ',') { row.push(cell); cell = ''; }
    else if (ch === '\n') { row.push(cell.replace(/\r$/, '')); rows.push(row); row = []; cell = ''; } else cell += ch;
  }
  if (cell || row.length) { row.push(cell); rows.push(row); }
  const [h, ...d] = rows; return d.filter(r => r.length === h.length).map(r => Object.fromEntries(h.map((k, i) => [k, r[i]])));
}
const sq = v => (v == null || v === '') ? 'NULL' : "N'" + String(v).replace(/'/g, "''") + "'";
const csvCell = v => /[",\n]/.test(String(v ?? '')) ? '"' + String(v).replace(/"/g, '""') + '"' : String(v ?? '');

const leads = Object.fromEntries(parseCSV(fs.readFileSync(CSV, 'utf8')).map(r => [r.OvertureID, r]));
const want = process.argv.slice(2);
const files = fs.readdirSync(DESIGNS).filter(f => f.endsWith('.json')).sort();
const all = files.map(f => JSON.parse(fs.readFileSync(path.join(DESIGNS, f), 'utf8')));
const pick = want.length ? all.filter(d => want.includes(d.Slug)) : all;
if (want.length && pick.length !== want.length) { console.error('Unknown design: ' + want.filter(w => !all.some(d => d.Slug === w)).join(', ')); process.exit(1); }

for (const d of pick) {
  const L = leads[d.OvertureID];
  if (!L) { console.error(`No lead in the sample CSV for ${d.Slug} (${d.OvertureID})`); process.exit(1); }
  const site = { ...d, CompanyName: L.CompanyName, Phone: L.Phone, Email: L.Email, Address: L.Address, City: L.City, County: L.County, Zip: L.Zip };
  const dir = path.join(ROOT, 'demo-sites', d.Slug);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'index.html'), render(site, { date: TODAY }));
  console.log(`built  ${d.Slug}  (${d.Layout} · ${d.Theme})`);
}

// manifest: every design, one row each
const cols = ['Slug', 'CompanyName', 'OvertureID', 'Layout', 'Theme', 'Status', 'Path', 'TemplateVersion', 'BuiltOn'];
const man = [cols.join(',')].concat(all.map(d => [d.Slug, (leads[d.OvertureID] || {}).CompanyName, d.OvertureID, d.Layout, d.Theme, d.Status,
  `demo-sites/${d.Slug}/index.html`, TEMPLATE_VERSION, TODAY].map(csvCell).join(',')));
fs.writeFileSync(path.join(ROOT, 'demo-sites', 'manifest.csv'), man.join('\n') + '\n');

// SQL for every design (insert-only, so edits made in the Admin site are never overwritten)
const values = all.map(d => '  (' + [sq(d.OvertureID), ...FIELDS.map(f => sq(d[f])), sq(`demo-sites/${d.Slug}/index.html`), sq(TEMPLATE_VERSION)].join(', ') + ')').join(',\n');
fs.writeFileSync(SQL, `-- Version: V2.0 (${TODAY}) — sql/05_demo_sites_built.sql — V2.0
-- Generated by admin-site/scripts/build-demos.js (SkyTech_WebsiteDeveloper). Safe to re-run; never creates duplicates.
-- 1) Adds each demo to dbo.DemoSites (one row per company). Rows that already exist are left alone, so edits made in the Admin site win.
-- 2) Marks the lead DemoBuilt (only if it is still New / Checked / NoSite) and logs one Note activity per demo.
-- Run in SSMS after sql/01 (V2.1) and sql/04 (V1.3).
USE SkyTechCRM;
SET NOCOUNT ON;
DECLARE @D TABLE (SourceRecordID NVARCHAR(64) PRIMARY KEY, ${FIELDS.map(f => `[${f}] NVARCHAR(MAX)`).join(', ')}, PreviewPath NVARCHAR(250), TemplateVersion VARCHAR(10));
INSERT INTO @D (SourceRecordID, ${FIELDS.map(f => `[${f}]`).join(', ')}, PreviewPath, TemplateVersion) VALUES
${values};

BEGIN TRANSACTION;
INSERT INTO dbo.DemoSites (CompanyID, ${FIELDS.map(f => `[${f}]`).join(', ')}, PreviewPath, TemplateVersion, BuiltBy)
SELECT c.CompanyID, ${FIELDS.map(f => `d.[${f}]`).join(', ')}, d.PreviewPath, d.TemplateVersion, 'SkyTech_WebsiteDeveloper'
FROM @D d JOIN dbo.Companies c ON c.SourceRecordID = d.SourceRecordID
WHERE NOT EXISTS (SELECT 1 FROM dbo.DemoSites x WHERE x.CompanyID = c.CompanyID OR x.Slug = d.Slug);

UPDATE l SET
  l.Status = CASE WHEN l.Status IN ('New', 'Checked', 'NoSite') THEN 'DemoBuilt' ELSE l.Status END,
  l.DemoURL = ISNULL(l.DemoURL, N'preview: ' + d.PreviewPath),
  l.AssignedAgent = CASE WHEN l.Status IN ('New', 'Checked', 'NoSite') THEN 'SkyTech_WebsiteDeveloper' ELSE l.AssignedAgent END,
  l.UpdatedOn = GETDATE()
FROM dbo.Leads l JOIN dbo.Companies c ON c.CompanyID = l.CompanyID JOIN @D d ON d.SourceRecordID = c.SourceRecordID
WHERE l.Status IN ('New', 'Checked', 'NoSite') OR l.DemoURL IS NULL;

INSERT INTO dbo.Activities (LeadID, Agent, ActivityType, Outcome, ActivityDate)
SELECT l.LeadID, 'SkyTech_WebsiteDeveloper', 'Note', N'Demo site built (' + d.TemplateVersion + N', ' + d.Theme + N'): ' + d.PreviewPath, GETDATE()
FROM dbo.Leads l JOIN dbo.Companies c ON c.CompanyID = l.CompanyID JOIN @D d ON d.SourceRecordID = c.SourceRecordID
WHERE NOT EXISTS (SELECT 1 FROM dbo.Activities a WHERE a.LeadID = l.LeadID AND a.Agent = 'SkyTech_WebsiteDeveloper'
                    AND a.Outcome LIKE N'Demo site built (' + d.TemplateVersion + N'%');
COMMIT TRANSACTION;

SELECT s.DemoID, s.BrandName, s.Theme, s.Status, l.Status AS LeadStatus
FROM dbo.DemoSites s JOIN @D d ON d.Slug = s.Slug LEFT JOIN dbo.Leads l ON l.CompanyID = s.CompanyID ORDER BY s.BrandName;
SELECT d.Slug AS NotFoundInDatabase FROM @D d WHERE NOT EXISTS (SELECT 1 FROM dbo.Companies c WHERE c.SourceRecordID = d.SourceRecordID);

-- Version: V2.0 (${TODAY}) — sql/05_demo_sites_built.sql — V2.0
`);
console.log(`${pick.length} built · ${all.length} designs in manifest · SQL: sql/05_demo_sites_built.sql`);

// Version: V1.0 (2026-10-05) — admin-site/scripts/build-demos.js — V1.0
