"""Version: V1.0 (2026-10-02) — scripts/website/content.py — V1.0
SkyTech_WebsiteDeveloper: wording and colours for each kind of business.

Rules for this file (owner-approved honesty rules, see agents/SkyTech_WebsiteDeveloper.md):
- No claims we cannot prove: no "licensed", "insured", "24/7", "years of experience",
  "free estimates", awards, prices or reviews. The owner of the business adds those.
- Service lists are typical for the trade and are shown as sample text until the owner confirms.
"""

AREAS = {
    "Baltimore City": ["Baltimore City", "Canton", "Fells Point", "Hampden", "Federal Hill", "Towson", "Dundalk"],
    "Baltimore County": ["Towson", "Catonsville", "Parkville", "Dundalk", "Owings Mills", "Pikesville", "Baltimore City"],
    "Howard": ["Columbia", "Ellicott City", "Laurel", "Elkridge", "Clarksville", "Jessup", "Savage"],
}

TRADE_STEPS = [
    ("Call or email", "Tell us what you need and where the job is."),
    ("Get a quote", "We look at the job and explain the options and the price."),
    ("Job done", "The work gets done and we make sure you are happy with it."),
]
REALTY_STEPS = [
    ("Talk with us", "Tell us what you are looking for, or about the property you have."),
    ("Make a plan", "We go over the market, the timing and the next steps together."),
    ("Move forward", "We guide you through each step until the job is done."),
]

# template: "trade" or "realty"; icon: key of ICONS in build_demo_sites.py
CATEGORIES = {
    "plumbing": dict(template="trade", label="Plumbing", icon="drop", accent="#1565c0", accent2="#0d3b75",
        tagline="Plumbing repairs and installations for homes and businesses",
        about="We are a local plumbing company. We handle everyday plumbing problems and bigger projects, and we explain the work before we start.",
        services=[("Leak repair", "Finding and fixing leaks in pipes, faucets and fixtures."),
                  ("Drain cleaning", "Clearing slow or blocked sinks, tubs, toilets and main lines."),
                  ("Water heaters", "Repair and replacement of tank and tankless water heaters."),
                  ("Fixture installation", "New faucets, toilets, sinks and showers, fitted properly."),
                  ("Pipe repair", "Repairing or replacing damaged and ageing pipes."),
                  ("Sump pumps", "Installing and servicing sump pumps to keep basements dry.")]),
    "hvac service": dict(template="trade", label="Heating & Air Conditioning", icon="temp", accent="#00838f", accent2="#004d55",
        tagline="Heating and cooling service to keep your home comfortable all year",
        about="We are a local heating and air conditioning company. We repair, install and maintain the systems that keep homes and businesses comfortable.",
        services=[("AC repair", "Getting your air conditioning running again when it stops cooling."),
                  ("Heating repair", "Furnace and heat pump repairs before the cold sets in."),
                  ("New systems", "Help choosing and installing a new heating or cooling system."),
                  ("Seasonal tune-ups", "Check-ups that help your system run better and last longer."),
                  ("Thermostats", "Installing and setting up standard and smart thermostats."),
                  ("Ductwork", "Repairing and sealing ducts for better airflow.")]),
    "electrician": dict(template="trade", label="Electrical Services", icon="bolt", accent="#e09f00", accent2="#7a4f00",
        tagline="Electrical repairs, upgrades and installations done right",
        about="We are a local electrical company working in homes and businesses, from small repairs to larger upgrades.",
        services=[("Repairs & troubleshooting", "Tracking down and fixing outlets, switches and circuits that stop working."),
                  ("Panel upgrades", "Upgrading electrical panels for modern power needs."),
                  ("Lighting", "Indoor, outdoor and recessed lighting installation."),
                  ("Outlets & switches", "Adding or replacing outlets, switches and dimmers."),
                  ("Ceiling fans", "Installing ceiling fans and light fixtures."),
                  ("EV chargers", "Installing home chargers for electric vehicles.")]),
    "roofing": dict(template="trade", label="Roofing", icon="roof", accent="#b23c17", accent2="#5e1f0b",
        tagline="Roof repairs and replacements that protect your home",
        about="We are a local roofing company. We fix leaks, repair damage and replace roofs, and we keep you informed along the way.",
        services=[("Roof repair", "Fixing leaks, missing shingles and worn areas."),
                  ("Roof replacement", "Complete tear-off and new roof installation."),
                  ("Inspections", "Checking your roof's condition after storms or before a sale."),
                  ("Storm damage", "Repairs after wind, hail and fallen-branch damage."),
                  ("Gutters", "Gutter and downspout repair and installation."),
                  ("Flashing & vents", "Sealing chimneys, skylights and roof vents.")]),
    "contractor": dict(template="trade", label="General Contracting", icon="hammer", accent="#37474f", accent2="#1c262b",
        tagline="Remodeling, repairs and building projects for your home",
        about="We are a local contracting company. We take on remodeling and repair projects and keep the job organized from start to finish.",
        services=[("Kitchen remodeling", "Updating layouts, cabinets, counters and finishes."),
                  ("Bathroom remodeling", "New tubs, showers, tile and vanities."),
                  ("Basements", "Turning unfinished basements into usable space."),
                  ("Decks & additions", "Building new outdoor and indoor living space."),
                  ("Drywall & painting", "Repairs, new walls and fresh paint."),
                  ("Flooring", "Installing hardwood, tile, vinyl and laminate floors.")]),
    "handyman": dict(template="trade", label="Handyman & Home Repair", icon="wrench", accent="#2e7d32", accent2="#174018",
        tagline="Home repairs and small jobs, handled for you",
        about="We are a local home repair service. We take care of the small and medium jobs on your list so you don't have to.",
        services=[("Home repairs", "Fixing the things around the house that need attention."),
                  ("Drywall patching", "Repairing holes, cracks and water damage."),
                  ("Painting", "Interior touch-ups and full rooms."),
                  ("Doors & windows", "Adjusting, repairing and replacing doors and hardware."),
                  ("Mounting & assembly", "TVs, shelves, furniture and fixtures."),
                  ("Carpentry", "Trim, small builds and wood repairs.")]),
    "gutter service": dict(template="trade", label="Power Washing & Gutters", icon="drop", accent="#0277bd", accent2="#01416b",
        tagline="Power washing and gutter care for a cleaner home",
        about="We are a local exterior cleaning company. We wash, clean and look after the outside of homes and businesses.",
        services=[("House washing", "Safe washing for siding and exterior walls."),
                  ("Decks & patios", "Cleaning wood, composite and stone surfaces."),
                  ("Driveways & walkways", "Removing dirt, stains and buildup from concrete."),
                  ("Gutter cleaning", "Clearing leaves and debris so water flows away."),
                  ("Gutter repair", "Fixing leaks, sagging sections and downspouts."),
                  ("Gutter guards", "Installing guards to keep gutters clear.")]),
    "real estate agent": dict(template="realty", label="Real Estate", icon="house", accent="#2e5e4e", accent2="#16332a",
        tagline="Helping you buy and sell homes with local know-how",
        about="I help buyers and sellers in the area make good decisions, from the first conversation to closing day.",
        note="Brokerage name and license details will be added here (required on Maryland real estate advertising).",
        services=[("Buying a home", "Finding homes that fit your needs and budget, and guiding your offer."),
                  ("Selling your home", "Pricing, preparing and marketing your home to the right buyers."),
                  ("Home value", "A market look at what your home could sell for today."),
                  ("First-time buyers", "Clear, step-by-step help for your first purchase."),
                  ("Relocation", "Help getting to know the area if you are moving here."),
                  ("Investment property", "Help finding and evaluating rental and investment homes.")]),
    "property management": dict(template="realty", label="Property Management", icon="key", accent="#3d4f7c", accent2="#1f2a45",
        tagline="Property management that looks after owners and tenants",
        about="We manage rental properties for owners in the area, handling the day-to-day work so you don't have to.",
        services=[("Tenant screening", "Finding reliable tenants through careful screening."),
                  ("Leasing", "Advertising vacancies, showing units and preparing leases."),
                  ("Rent collection", "Collecting rent and keeping clear records."),
                  ("Maintenance", "Coordinating repairs and regular upkeep."),
                  ("Inspections", "Move-in, move-out and routine property checks."),
                  ("Owner reports", "Regular updates on income, costs and property condition.")]),
    "mortgage lender": dict(template="realty", label="Mortgage Services", icon="house", accent="#5b3f8c", accent2="#2f2049",
        tagline="Home financing explained clearly, from pre-approval to closing",
        about="We help home buyers and owners understand their financing options and move through the loan process with confidence.",
        note="NMLS number and lending disclosures will be added here (required on mortgage advertising).",
        services=[("Home purchase loans", "Financing for buying your next home."),
                  ("Refinancing", "Reviewing whether a refinance makes sense for you."),
                  ("Pre-approval", "Knowing your budget before you start shopping."),
                  ("First-time buyers", "Guidance through every step of your first loan."),
                  ("Loan options", "Clear explanations of the options available to you."),
                  ("Local help", "A local contact you can call with questions.")]),
}

# Per-company adjustments where the generic category does not fit (from BackOffice evidence).
OVERRIDES = {
    "The Catonsville CUBE": dict(category="property management", label="Office Space", icon="key",
        tagline="Office space for local professionals and small businesses",
        about="We offer office space for professionals and small businesses who want a place to work and meet clients.",
        services=[("Private offices", "Your own office space for focused work."),
                  ("Shared workspace", "Flexible desk space when you need it."),
                  ("Meeting space", "A professional place to meet clients."),
                  ("Flexible terms", "Options that fit how your business works."),
                  ("Local community", "Work alongside other local businesses."),
                  ("Tours", "Call to arrange a visit.")]),
    "Hoco Power Wash": dict(category="gutter service"),
}

# Version: V1.0 (2026-10-02) — scripts/website/content.py — V1.0
