-- Version: V1.0 (2026-10-02) — sql/05_demo_sites_built.sql — V1.0
-- Generated by scripts/website/build_demo_sites.py (SkyTech_WebsiteDeveloper). Safe to re-run: no duplicates.
-- Marks the leads that have a demo site as DemoBuilt (only if they are still New / Checked / NoSite),
-- fills DemoURL if empty, and logs one Note activity per demo. Run in SSMS after the owner approves the demos.
USE SkyTechCRM;
SET NOCOUNT ON;
DECLARE @Demos TABLE (SourceRecordID NVARCHAR(64) PRIMARY KEY, CompanyName NVARCHAR(200), DemoURL NVARCHAR(250), TemplateVersion VARCHAR(10));
INSERT INTO @Demos (SourceRecordID, CompanyName, DemoURL, TemplateVersion) VALUES
  (N'923dfc84-9ee4-4a75-a993-bb9b9e64fd57', N'C&A Plumbing', N'preview: demo-sites/c-and-a-plumbing-20723/index.html', N'V1.0'),
  (N'8b5c02c7-d0ca-4256-a072-dfbb9fbd14a5', N'David P Davis Construction', N'preview: demo-sites/david-p-davis-construction-21228/index.html', N'V1.0'),
  (N'c3420521-ee3e-4ebb-b77e-b735849b8628', N'Lee Newton Co.', N'preview: demo-sites/lee-newton-co-21217/index.html', N'V1.0');

BEGIN TRANSACTION;
UPDATE l SET
  l.Status = CASE WHEN l.Status IN ('New', 'Checked', 'NoSite') THEN 'DemoBuilt' ELSE l.Status END,
  l.DemoURL = ISNULL(l.DemoURL, d.DemoURL),
  l.AssignedAgent = CASE WHEN l.Status IN ('New', 'Checked', 'NoSite') THEN 'SkyTech_WebsiteDeveloper' ELSE l.AssignedAgent END,
  l.UpdatedOn = GETDATE()
FROM dbo.Leads l
JOIN dbo.Companies c ON c.CompanyID = l.CompanyID
JOIN @Demos d ON d.SourceRecordID = c.SourceRecordID
WHERE l.Status IN ('New', 'Checked', 'NoSite') OR l.DemoURL IS NULL;

INSERT INTO dbo.Activities (LeadID, Agent, ActivityType, Outcome, ActivityDate)
SELECT l.LeadID, 'SkyTech_WebsiteDeveloper', 'Note', N'Demo site built (' + d.TemplateVersion + N'): ' + d.DemoURL, GETDATE()
FROM dbo.Leads l
JOIN dbo.Companies c ON c.CompanyID = l.CompanyID
JOIN @Demos d ON d.SourceRecordID = c.SourceRecordID
WHERE NOT EXISTS (SELECT 1 FROM dbo.Activities a WHERE a.LeadID = l.LeadID AND a.Agent = 'SkyTech_WebsiteDeveloper'
                    AND a.Outcome LIKE N'Demo site built%' + d.DemoURL);
COMMIT TRANSACTION;

SELECT c.CompanyName, l.Status, l.DemoURL
FROM dbo.Leads l JOIN dbo.Companies c ON c.CompanyID = l.CompanyID
JOIN @Demos d ON d.SourceRecordID = c.SourceRecordID ORDER BY c.CompanyName;
SELECT d.CompanyName AS NotFoundInDatabase FROM @Demos d
WHERE NOT EXISTS (SELECT 1 FROM dbo.Companies c WHERE c.SourceRecordID = d.SourceRecordID);

-- Version: V1.0 (2026-10-02) — sql/05_demo_sites_built.sql — V1.0
