-- Version: V2.0 (2026-10-05) — sql/05_demo_sites_built.sql — V2.0
-- Generated by admin-site/scripts/build-demos.js (SkyTech_WebsiteDeveloper). Safe to re-run; never creates duplicates.
-- 1) Adds each demo to dbo.DemoSites (one row per company). Rows that already exist are left alone, so edits made in the Admin site win.
-- 2) Marks the lead DemoBuilt (only if it is still New / Checked / NoSite) and logs one Note activity per demo.
-- Run in SSMS after sql/01 (V2.1) and sql/04 (V1.3).
USE SkyTechCRM;
SET NOCOUNT ON;
DECLARE @D TABLE (SourceRecordID NVARCHAR(64) PRIMARY KEY, [Slug] NVARCHAR(MAX), [Layout] NVARCHAR(MAX), [Theme] NVARCHAR(MAX), [PrimaryColor] NVARCHAR(MAX), [AccentColor] NVARCHAR(MAX), [BackgroundColor] NVARCHAR(MAX), [HeadingFont] NVARCHAR(MAX), [BodyFont] NVARCHAR(MAX), [LogoText] NVARCHAR(MAX), [LogoShape] NVARCHAR(MAX), [Illustration] NVARCHAR(MAX), [BrandName] NVARCHAR(MAX), [Tagline] NVARCHAR(MAX), [Headline] NVARCHAR(MAX), [Subheadline] NVARCHAR(MAX), [About] NVARCHAR(MAX), [Services] NVARCHAR(MAX), [Highlights] NVARCHAR(MAX), [Steps] NVARCHAR(MAX), [ServiceAreas] NVARCHAR(MAX), [CallToAction] NVARCHAR(MAX), [DisclosureNote] NVARCHAR(MAX), [Status] NVARCHAR(MAX), [Notes] NVARCHAR(MAX), PreviewPath NVARCHAR(250), TemplateVersion VARCHAR(10));
INSERT INTO @D (SourceRecordID, [Slug], [Layout], [Theme], [PrimaryColor], [AccentColor], [BackgroundColor], [HeadingFont], [BodyFont], [LogoText], [LogoShape], [Illustration], [BrandName], [Tagline], [Headline], [Subheadline], [About], [Services], [Highlights], [Steps], [ServiceAreas], [CallToAction], [DisclosureNote], [Status], [Notes], PreviewPath, TemplateVersion) VALUES
  (N'923dfc84-9ee4-4a75-a993-bb9b9e64fd57', N'c-and-a-plumbing-20723', N'split', N'Fresh Water', N'#0b2545', N'#12b5a5', N'#ffffff', N'Plus Jakarta Sans', N'Inter', N'C&A', N'drop', N'plumbing-home', N'C&A Plumbing', N'Plumbing in Laurel, MD', N'Your neighborhood plumber for leaks, drains and water heaters', N'From a dripping faucet to a new water heater, C&A Plumbing finds the problem, explains the fix and gets your water running right again.', N'We are a local plumbing company serving homes and businesses in Laurel and across Howard County. Everyday repairs or bigger projects, we explain the work and the price before we start.', N'Leak repair | Finding and fixing leaks in pipes, faucets and fixtures before they cause damage.
Drain cleaning | Clearing slow or blocked sinks, tubs, toilets and main lines.
Water heaters | Repair and replacement of tank and tankless water heaters.
Fixture installation | New faucets, toilets, sinks and showers, fitted properly.
Pipe repair | Repairing or replacing damaged and ageing pipes.
Sump pumps | Installing and servicing sump pumps to keep basements dry.', N'Clear quote first | You know the price before any work begins.
Respect for your home | Tidy work areas and care around your floors and fixtures.
Local to Laurel | Serving homes and businesses across Howard County.', N'Call or email | Tell us what is happening and where.
Get a clear quote | We look at the problem and explain your options.
Fixed and tested | We finish the job and check everything works.', N'Laurel, Columbia, Ellicott City, Elkridge, Savage, Jessup, Clarksville', N'Call for a quote', NULL, N'ReadyForReview', N'Concept logo and artwork; replace with the owner''s logo and photos after sign-up.', N'demo-sites/c-and-a-plumbing-20723/index.html', N'V2.0'),
  (N'8b5c02c7-d0ca-4256-a072-dfbb9fbd14a5', N'david-p-davis-construction-21228', N'bold', N'Blueprint', N'#1d2329', N'#f2a33a', N'#f4f1ea', N'Barlow Condensed', N'Barlow', N'DPD', N'roof', N'house-frame', N'David P Davis Construction', N'Remodeling in Catonsville, MD', N'Plan it right. Build it to last.', N'Kitchens, baths, basements and decks. David P Davis Construction plans the job with you and keeps the work organized from the first measurement to the final walkthrough.', N'We are a local contracting company in Catonsville taking on remodeling and home improvement projects across Baltimore County. One team, a clear plan and a tidy job site.', N'Kitchen remodeling | New layouts, cabinets, counters and finishes for the heart of your home.
Bathroom remodeling | Updated tubs, showers, tile and vanities.
Basement finishing | Turning unfinished space into rooms you will use.
Decks & outdoor living | Decks and porches built for Maryland seasons.
Additions | More room for your family without moving.
Repairs & carpentry | Trim, doors, drywall and the jobs in between.', N'One point of contact | You always know who to call about your project.
Clear scope and schedule | We agree what is included and when, before work begins.
Clean job site | Work areas kept safe and tidy every day.', N'Talk it through | Tell us about the project and your goals.
Plan and quote | We measure, plan and give you a written quote.
Build | Work proceeds on the agreed schedule.
Walkthrough | We finish the details and walk the job with you.', N'Catonsville, Arbutus, Ellicott City, Woodlawn, Towson, Pikesville, Owings Mills, Baltimore City', N'Call to plan your project', N'Maryland Home Improvement Commission (MHIC) license number will be shown here (required on home improvement advertising).', N'ReadyForReview', N'Concept logo and artwork; replace with the owner''s logo and project photos after sign-up.', N'demo-sites/david-p-davis-construction-21228/index.html', N'V2.0'),
  (N'c3420521-ee3e-4ebb-b77e-b735849b8628', N'lee-newton-co-21217', N'classic', N'Harbor Classic', N'#1f3d33', N'#b8955a', N'#f8f4ec', N'Playfair Display', N'Source Sans 3', N'LN', N'arch', N'rowhouses', N'Lee Newton Co.', N'Property Management · Baltimore', N'Property management with a personal touch', N'Lee Newton Co. looks after rental homes in Baltimore: finding good residents, handling repairs and keeping owners informed.', N'We manage rental properties for owners in Baltimore and nearby neighborhoods, handling the day-to-day work so owners can relax and residents feel at home.', N'Tenant screening | Careful screening to find reliable residents.
Leasing & marketing | Advertising vacancies, showings and lease preparation.
Rent collection | Collecting rent on time and keeping clear records.
Maintenance coordination | Arranging repairs and regular upkeep.
Property inspections | Move-in, move-out and routine property checks.
Owner reporting | Regular updates on income, costs and condition.', N'For property owners | One local contact who looks after your property, your residents and your paperwork.
For residents | A responsive office for questions, repairs and renewals.
Know the neighborhood | Local experience with Baltimore rowhouses and rental homes.
Clear communication | Regular updates so nothing is a surprise.', N'Get in touch | Tell us about your property or rental needs.
Meet and review | We walk the property and explain how we work.
We take it from here | Leasing, rent and maintenance handled for you.', N'Baltimore City, Reservoir Hill, Bolton Hill, Druid Heights, Mondawmin, Mount Vernon, Towson', N'Call our office', N'Maryland real estate brokerage license details will be shown here (required for leasing and property management).', N'ReadyForReview', N'Concept logo and artwork; no email on public listings, confirm by phone.', N'demo-sites/lee-newton-co-21217/index.html', N'V2.0');

BEGIN TRANSACTION;
INSERT INTO dbo.DemoSites (CompanyID, [Slug], [Layout], [Theme], [PrimaryColor], [AccentColor], [BackgroundColor], [HeadingFont], [BodyFont], [LogoText], [LogoShape], [Illustration], [BrandName], [Tagline], [Headline], [Subheadline], [About], [Services], [Highlights], [Steps], [ServiceAreas], [CallToAction], [DisclosureNote], [Status], [Notes], PreviewPath, TemplateVersion, BuiltBy)
SELECT c.CompanyID, d.[Slug], d.[Layout], d.[Theme], d.[PrimaryColor], d.[AccentColor], d.[BackgroundColor], d.[HeadingFont], d.[BodyFont], d.[LogoText], d.[LogoShape], d.[Illustration], d.[BrandName], d.[Tagline], d.[Headline], d.[Subheadline], d.[About], d.[Services], d.[Highlights], d.[Steps], d.[ServiceAreas], d.[CallToAction], d.[DisclosureNote], d.[Status], d.[Notes], d.PreviewPath, d.TemplateVersion, 'SkyTech_WebsiteDeveloper'
FROM @D d JOIN dbo.Companies c ON c.SourceRecordID = d.SourceRecordID
WHERE NOT EXISTS (SELECT 1 FROM dbo.DemoSites x WHERE x.CompanyID = c.CompanyID OR x.Slug = d.Slug);

UPDATE l SET
  l.Status = CASE WHEN l.Status IN ('New', 'Checked', 'NoSite') THEN 'DemoBuilt' ELSE l.Status END,
  l.DemoURL = ISNULL(l.DemoURL, N'preview: ' + d.PreviewPath),
  l.AssignedAgent = CASE WHEN l.Status IN ('New', 'Checked', 'NoSite') THEN 'SkyTech_WebsiteDeveloper' ELSE l.AssignedAgent END,
  l.UpdatedOn = GETDATE()
FROM dbo.Leads l JOIN dbo.Companies c ON c.CompanyID = l.CompanyID JOIN @D d ON d.SourceRecordID = c.SourceRecordID
WHERE l.Status IN ('New', 'Checked', 'NoSite') OR l.DemoURL IS NULL;

INSERT INTO dbo.Activities (LeadID, Agent, ActivityType, Outcome, ActivityDate)
SELECT l.LeadID, 'SkyTech_WebsiteDeveloper', 'Note', N'Demo site built (' + d.TemplateVersion + N', ' + d.Theme + N'): ' + d.PreviewPath, GETDATE()
FROM dbo.Leads l JOIN dbo.Companies c ON c.CompanyID = l.CompanyID JOIN @D d ON d.SourceRecordID = c.SourceRecordID
WHERE NOT EXISTS (SELECT 1 FROM dbo.Activities a WHERE a.LeadID = l.LeadID AND a.Agent = 'SkyTech_WebsiteDeveloper'
                    AND a.Outcome LIKE N'Demo site built (' + d.TemplateVersion + N'%');
COMMIT TRANSACTION;

SELECT s.DemoID, s.BrandName, s.Theme, s.Status, l.Status AS LeadStatus
FROM dbo.DemoSites s JOIN @D d ON d.Slug = s.Slug LEFT JOIN dbo.Leads l ON l.CompanyID = s.CompanyID ORDER BY s.BrandName;
SELECT d.Slug AS NotFoundInDatabase FROM @D d WHERE NOT EXISTS (SELECT 1 FROM dbo.Companies c WHERE c.SourceRecordID = d.SourceRecordID);

-- Version: V2.0 (2026-10-05) — sql/05_demo_sites_built.sql — V2.0
